import "@radix-ui/themes/styles.css";
import "./globals.css";
import type { Metadata } from "next";
import localFont from "next/font/local";
import { Theme, ThemePanel } from "@radix-ui/themes";
import Navigator from "@/app/Navigator";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" dir="ltr">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Theme appearance="light" accentColor="violet">
        {/* <Theme> */}
          <Navigator />
          <main className="p-5">
            {children}
          </main>
          <ThemePanel/>
        </Theme>
      </body>
    </html>
  );
}
